#!/usr/bin/env bash

yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
#yabai -m config window_border                off
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0


yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Digital Color Meter$" sticky=on layer=above manage=off
yabai -m rule --add app="^Cisco" manage=off
yabai -m rule --add app="^Karabiner-Elements$" sticky=on layer=above manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" sticky=on layer=above manage=off
#yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add app="^JetBrains Toolbox$" manage=off
jetbrain_apps="^(IntelliJ IDEA|WebStorm|PyCharm|CLion|GoLand)$"
yabai -m rule --add app="${jetbrain_apps}" title="^(Preferences|Project Structure|Plugins|Run/Debug Configurations|Edit configuration settings)$" manage=off
#jetbrains_floating_windows='.*Preferences*.|.*Project Structure*.|.*Plugins*.|.*Run/Debug Configurations*.|.*Edit configuration settings*.|.*Welcome*.|Checkout*.|.*Configurations|Choose*.|Import*.|.*Changes|Tip*.|Rename*.'
#yabai -m rule --add app="${jetbrain_apps}" title="${jetbrains_floating_windows}" manage=off
#yabai -m rule --add app="${jetbrain_apps}" manage=off

echo "yabai configuration loaded.."

yabai -m space 2 --layout stack

bindAppToSpace() {
  local appName=$1
  local spaceNumber=$2
  yabai -m rule --add app="^$appName$" space="$spaceNumber"
  yabai -m signal --add event=application_launched app="^$appName$" action="skhd -k 'hyper - $spaceNumber'"
}

bindAppToSpace "Firefox" 1
bindAppToSpace "IntelliJ IDEA" 2
bindAppToSpace "Microsoft Outlook" 3
bindAppToSpace "Microsoft Teams" 3
bindAppToSpace "Sublime Text" 4
#bindAppToSpace "Terminal" 5
bindAppToSpace "Spotify" 9
